require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
  Exclude:
    - 'script/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'

Lint/HandleExceptions:
  Exclude:
    - 'spec/unit/**/*'
    - 'spec/integration/**/*'

Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Exclude:

Metrics/CyclomaticComplexity:
  Exclude:

Metrics/PerceivedComplexity:
  Exclude:

Metrics/ModuleLength:
  Exclude:

Metrics/ClassLength:
  Description: Avoid classes longer than 100 lines of code.
  Enabled: false
  CountComments: false
  Max: 100

Metrics/MethodLength:
  Enabled: false

Style/MethodName:
  Exclude:
# MK -- I've disabled this because we do a lot of 'and returns'
Style/AndOr:
  Enabled: false

Style/AccessorMethodName:
  Exclude:

Style/PredicateName:
  Exclude:

Style/GuardClause:
  Exclude:

Style/TrivialAccessors:
  Exclude:

Style/EachWithObject:
  Exclude:

Style/CaseEquality:
  Exclude:

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/Semicolon:
  Exclude:
    - 'spec/**/*'

Style/Lambda:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude:

Style/SignalException:
  Enabled: false

Style/FileName:
  Exclude:

Rails/Output:
  Exclude:
    - 'lib/generators/**/*'

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/DescribedClass:
  Exclude:
