language: ruby
rvm:
  - 2.0.0

sudo: false
cache: bundler

notifications:
  email:
    - tdl-commiters@googlegroups.com

before_script:
  - cp config/fedora.yml.sample config/fedora.yml
  - cp config/solr.yml.sample config/solr.yml
  - cp config/devise.yml.sample config/devise.yml
  - cp config/application.yml.sample config/application.yml
  - cp config/database.yml.travis config/database.yml
  - cp config/ldap.yml.sample config/ldap.yml
  - mysql -e 'create database tdl_test'
  - mkdir -p tmp && export TMPDIR=tmp
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - TRAVIS=true

bundler_args: --without development debug

services:
  - mysql
